### PR TITLE
Helpers for semantic version

### PR DESCRIPTION
**Pull request by snimavat**
connect #1

### CODE REVIEW

**Review by jdabal — COMMENTED** [review]
so in our version.properties on most projects we have 
version=X.Y.X (major.minor.patch) so invrement version will change which part ? what it `semver bump` ?

Sudhir/Joanna slack:

- semver bump is our custom bash command

- prerel will bum last part of version x.y.x-RCx
- prerel bumpx RC x
- patch bumps last .x

- semver can be used to bump any of the major.minor.patch.RC.x

- So for RCM if we have  version `version=10.0.2` it will make `version=10.0.3` for rcm it will bump the last patch version

- bash.sh defines it, if we use RCx for rcm, we will have to once update bash.sh to bump prerel instead of patch and than it keeps working

- its all automatic, we dont do any of this manually, we have just make release, we dont tag, or bump version our self, doing a release will do it

**Still my question (add to README !) on simple cases:**
- automatically bumb prelel version
- how to change prelel version if I decide to change version from X.Y.Z to X.Y.Z-RC1
- how to bump major or minor version?

**Comment by basejump** [comment]
z.y.x-RCa is not valid, it would be x.y.x-RC.a
a normal increment would only bump last number, in this case would increment a
this should mirror our gradle-plugin in yakworks.

**Comment by jdabal** [comment]
@snimavat

**1.  I have no idea how to test it, put steps in Readme on how to use it.**

My steps were:
- added version.properties with `version=1.2.3-RC.1`
- was looking for the function that I should call that will change version to `1.2.3-RC.2`
- I only found updateVersion so I ran it 

```
BMUSSER-LT:~ joanna$ cd play/bin
BMUSSER-LT:bin joanna$ . ./build_functions.sh
BMUSSER-LT:bin joanna$ updateVersion 2
```

and it made my version `2` :-(

you have make function to print version , how do I call it ?

Can we even test it inside this project or do I need to have rcm or ar-api ? It would be good to have it tested on what it does here.

**2. make sure we have valid versions that gradle will accept**
1.0.1-RC or  1.0.1-RC1  will not work with gradle plugin
1.0.1 and 1.0.1-RC.1 will work

**3. is `prelel` the last part of version ? Is it what they call it here https://semver.org/ `pre-release` ? Can we call it `pre-release` ?**

**Please put comments on functions and Readme on how to use it and what it does. How to test it inside this project and how to use it in rcm or ar-api.**

**Comment by snimavat** [comment]
https://github.com/9ci/rcm/pull/4911

**Pull request merged**
